#pragma once

#include "NativeGameplayTags.h"


namespace GameTags
{
	//////Input Tags//////
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Aim);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_Reload);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_Shoot);
	
	
	
	//////Movement//////
	//State
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_State);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_State_Sprinting);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_State_Crouching);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_State_Aiming);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_State_Mantling);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_State_SprintRecovery);
	
}