#pragma once

#include "NativeGameplayTags.h"


namespace GameTags
{
	//////Input Tags//////
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Aim);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Reload);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Shoot);
	
	
	
	//////Movement//////
	//State
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_State);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_State_Idle);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_State_Walking);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_State_Falling);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_State_Sprinting);

	
	//Blocking
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Blocked);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Blocked_Walking);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Blocked_Jumping);
	MDA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Blocked_Sprinting);

	
	
	
	
}

